check_android_task:
  name: Run Android instrumented tests
  env:
    SCREENSHOTS_ROOT_DIR: /data/data/ru.nikitae57.cirrussandbox/files/screenshots
  skip: $CIRRUS_PR_LABELS =~ ".*no_ui_testing_required.*"
  only_if: $CIRRUS_PR != '' && $CIRRUS_BASE_BRANCH == 'master'

  container:
    image: cirrusci/android-sdk:30
    kvm: true
    cpu: 6
    memory: 24G
  asdas_script:
    echo $CIRRUS_PR_LABELS
  licenses_script:
    echo yes | sdkmanager --licenses
  install_emulator_script:
    sdkmanager --install "system-images;android-30;default;x86_64"
  create_device_script:
    echo no | avdmanager create avd --force
    -n test
    -k "system-images;android-30;default;x86_64"
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator
    -avd test
    -no-audio
    -no-window
  assemble_instrumented_tests_script:
    ./gradlew assembleDebugAndroidTest
  wait_for_emulator_script:
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
  disable_animations_script: |
    adb shell settings put global window_animation_scale 0.0
    adb shell settings put global transition_animation_scale 0.0
    adb shell settings put global animator_duration_scale 0.0
  check_script: ./gradlew connectedDebugAndroidTest || mkdir screenshots && adb root && for i in {1..5}; do adb pull $SCREENSHOTS_ROOT_DIR screenshots && break || sleep 5; done && return 1
  on_failure :
    publish_report_artifacts:
      path: "app/build/reports/androidTests/connected/**/*"
    publish_screenshots_artifacts:
      path: "screenshots/**/*"
