check_android_task:
  name: Run Android instrumented tests
#  only_if: $CIRRUS_PR != '' && $CIRRUS_BASE_BRANCH == $CIRRUS_DEFAULT_BRANCH

  container:
    image: cirrusci/android-sdk:30
    kvm: true
    cpu: 6
    memory: 24G

  tmp_script:
    echo "$CIRRUS_BASE_BRANCH"
    echo "$CIRRUS_PR"
    echo "$CIRRUS_DEFAULT_BRANCH"

  licenses_script:
    echo yes | sdkmanager --licenses
  install_emulator_script:
    sdkmanager --install "system-images;android-30;default;x86_64"
  create_device_script:
    echo no | avdmanager create avd --force
    -n test
    -k "system-images;android-30;default;x86_64"
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator
    -avd test
    -no-audio
    -no-window
  assemble_instrumented_tests_script:
    ./gradlew assembleDebugAndroidTest
  wait_for_emulator_script:
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
  disable_animations_script: |
    adb shell settings put global window_animation_scale 0.0
    adb shell settings put global transition_animation_scale 0.0
    adb shell settings put global animator_duration_scale 0.0
  check_script: ./gradlew connectedDebugAndroidTest
  on_failure :
    publish_report_artifacts:
      path: "app/build/reports/androidTests/connected/**/*"
    echo_artifacts_url_script:
      echo "artifacts url - https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/publish_report.zip" && return 1
